{% set name = "dwgsim" %}
{% set version = "0.1.12" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/nh13/{{ name|upper }}/archive/{{ name }}.{{ version }}.tar.gz
  sha256: 230abcbc7e437dcfbb6a66a6639baa4e6d75d5186caa93fd3ee8743a824637e7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - ncurses
  run:
    - zlib
    - ncurses

test:
  commands:
    - printf ">a\nAAAAA" > ref.fa; dwgsim ref.fa pref

extra:
  recipe-maintainer:
    - clintval

about:
  home: https://github.com/nh13/{{ name|upper }}
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL
  summary: 'Whole Genome Simulator for Next-Generation Sequencing'
  doc_url: https://github.com/nh13/{{ name|upper }}/wiki
