{% set version = "0.8.0" %}

package:
  name: cooler
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/c/cooler/cooler-{{ version }}.tar.gz
  sha256: 5817c5ae5ac1e50bb1ce8585678127868b956a20236f60009775809b57c64c4b

build:
  number: 0
  entry_points:
    - cooler = cooler.cli:cli

requirements:
  host:
    - python
    - setuptools
    - zlib

  run:
    - zlib
    - hdf5
    - python
    - six
    - multiprocess
    - numpy
    - scipy
    - pandas
    - h5py
    - dask
    - cytoolz
    - click
    - biopython
    - pysam >0.8
    - pyfaidx
    - pairix

test:
  imports:
    - cooler
    - cooler.cli
    - cooler.contrib

  commands:
    # click requires a unicode locale
    - cooler --help

about:
  home: https://github.com/mirnylab/cooler
  license: BSD
  summary: 'Sparse binary format for genomic interaction matrices'

extra:
  container:
    # click requires a unicode locale when used with Python 3
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true  # [py3k]
